#General
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

#see https://fabricmc.net/develop/
minecraft_version=25w36b
yarn_mappings=16
loader_version=0.17.2
#Fabric api
fabric_api_version=0.133.1+1.21.9

elmendorf_version=0.16.0

immersive_portals_version=v6.0.3-mc1.21.1

#Publishing
mod_version = 7.1.0-beta.1
curseforge_id = 318449
modrinth_id = K01OU20C
curseforge_versions = 1.21.9-snapshot
modrinth_versions = 25w36b
release_type = beta
display_name = Cardinal-Components-API
owners = Ladysnake

# Licensing
license_header = MIT
