#General
org.gradle.jvmargs = -Xmx3G
org.gradle.parallel=true
fabric.loom.multiProjectOptimisation=true

#see https://fabricmc.net/develop/
minecraft_version=25w20a
yarn_mappings=1
loader_version=0.16.14
#Fabric api
fabric_api_version=0.124.1+1.21.6

elmendorf_version=0.15.0

immersive_portals_version=v6.0.3-mc1.21.1

#Publishing
mod_version = 7.0.0-alpha.1+25w20a
curseforge_id = 318449
modrinth_id = K01OU20C
curseforge_versions = 1.21.6-Snapshot
modrinth_versions = 25w20a
release_type = alpha
display_name = Cardinal-Components-API
owners = Ladysnake

# Licensing
license_header = MIT
