dependencies {
    // Need to add the base module to the annotation classpath too, otherwise the mixin obf AP chokes on ComponentProvider
    // (which we add to various classes through interface injection)
    annotationProcessor api(project(":cardinal-components-base"))
    testmodImplementation project(":cardinal-components-base").sourceSets.testmod.output
}
